language: node_js
cache: yarn
node_js:
  - node
  - "12"
  - "10"
before_deploy: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: test/demo/build
  "on":
    branch: next
    node_js: node
env:
  - FORCE_COLOR=1
